global_frame: map
rolling_window: true

obstacle_range: 0.8
raytrace_range: 2.0

plugins:
  - {name: obstacles_laser2,           type: "costmap_2d::ObstacleLayer"}
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}