footprint: [[0.21, 0.22], [0.21, -0.22], [-0.21, -0.22], [-0.21, 0.22]]
footprint_padding: 0.05

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 10 #????

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 4.0

#layer definitions
# static:
#     map_topic: /map
#     subscribe_to_updates: true

obstacles_laser2:
    observation_sources: depth_sensor
    depth_sensor: {data_type: PointCloud2, clearing: true, marking: true, topic: /zed2/point_cloud/cloud_registered, sensor_frame: zed2_camera_center, min_obstacle_height: -0.03, obstacle_range: 0.8, raytrace_range: 2}
obstacles_laser:
    observation_sources: depth_sensor
    depth_sensor: {data_type: PointCloud2, clearing: true, marking: true, topic: /zed2/point_cloud/cloud_registered, sensor_frame: zed2_camera_center, min_obstacle_height: 0.25, obstacle_range: 2.5, raytrace_range: 5}

inflation:
    inflation_radius: 1.0
