
global_frame: map
robot_base_frame: base_link
update_frequency: 2
publish_frequency: 1
width: 200.0
height: 200.0
origin_x: -100.0
origin_y: -100.0
resolution: 0.08
static_map: false
rolling_window: false
# footprint: [[2.0, 2.0], [-2.0, 2.0], [2.0, -2.0], [-2.0, -2.0]]


plugins: 
  # - {name: static_map,       type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,   type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

inflation_layer:
  transform_tolerance: 1
  # obstacle_range: 0.5
  # raytrace_range: 0.5
  inflation_radius: 1.0
  cost_scaling_factor: 5
  lethal_cost_threshold: 100
