global_frame: map
rolling_window: true

obstacle_range: 0.8
raytrace_range: 2.0

width: 6.0
height: 6.0

origin_x: -3.0
origin_y: -3.0

plugins:
  - {name: obstacles_laser2,           type: "costmap_2d::ObstacleLayer"}
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}