controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0.0
max_planning_retries: 5

# Planner plugins
base_global_planner: global_planner/GlobalPlanner
base_local_planner: base_local_planner/TrajectoryPlannerROS
# Recovery behavior parameters

recovery_behavior_enabled: true
clearing_rotation_allowed: false
conservative_reset_dist: 10



GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 5
  cost_factor: 3.0
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1
  global_frame_id: map